export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const SET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const FETCH_PRODUCTS_LIST_ERROR = 'FETCH_PRODUCTS_LIST_ERROR';